version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEST_DEBUG=1
      - NODE_ENV
      - DB_PASSWORD
      - DB_USER
      - DB_NAME
      - DB_HOST=postgres
      - DB_PORT
    volumes:
      - ./src:/usr/src/app/src:rw
    ports:
      - "3000:3000"
      - "9229:9229"

  postgres:
    image: postgres:17.3
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
